apiVersion: v1
kind: Pod
metadata:
  name: myfirstnodeapp
spec:
  containers:
    - name: whatever
      image: balu0311/nodeapp:latest
      imagePullPolicy: Always
      command: [ "echo", "SUCCESS" ]
  imagePullSecrets:
    - name: myregistrykey
